version = 0.1
[default]

[default.deploy]

[default.deploy.parameters]
stack_name = "ocr-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d3fer2tg3hmb"
s3_prefix = "ocr-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "UserEmail=\"saudmh@amazon.sa\""